spring:
  application:
    name: OAuth2Application

app:
  github:
    client-id: Ov23lio6MKR3YnArx8aI
    client-secret: 662a7a6ca89a77a0c3f47aa09d312b5b7d76e083
    authorize-url: https://github.com/login/oauth/authorize
    token-url: https://github.com/login/oauth/access_token
    user-url: https://api.github.com/user
    emails-url: https://api.github.com/user/emails
    scope: read:user user:email
  jwt:
    issuer: ${APP_JWT_ISSUER:http://localhost:8080}
    audience: ${APP_JWT_AUDIENCE:api://default}
    access-token-expiry-seconds: 900     # 15 min
    refresh-token-expiry-seconds: 2592000 # 30 days
    private-key-pem: ${APP_JWT_PRIVATE_KEY}   # PEM string or path (see README)
    public-key-pem: ${APP_JWT_PUBLIC_KEY}
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:3000}

security:
  oauth:
    state-cookie-name: OAUTH2_STATE
    state-cookie-max-age-seconds: 300
#authorization-uri: https://github.com/login/oauth/authorize
#token-uri: https://github.com/login/oauth/access_token
#user-info-uri: https://api.github.com/user
